server:
  port: 8001

spring:
  application:
    name: cambio-service
  datasource:
    hikari:
      driver-class-name: ${DRIVER}
      jdbc-url: ${JDBC_URL}
      username: ${DB_USERNMAE}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT}
  flyway:
    url: ${DB_URL}
    schemas: ${SCHEMA}
    user: ${DB_USERNMAE}
    password: ${DB_PASSWORD}