version: '3.4'

services:
  cambio-db:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3308"
    expose:
      - 3308
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: cambio-service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    networks:
      - microservices-network
  book-db:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3310:3310"
    expose:
      - 3310
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: book-service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    networks:
      - microservices-network
  naming-server:
    image: pabloaugustocm/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - microservices-network
  api-gateway:
    image: pabloaugustocm/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABIITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - microservices-network
  cambio-service:
    image: pabloaugustocm/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - api-gateway
      - cambio-db
      - rabbit-mq
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin
      SPRING.FLYWAY.SCHEMAS: cambio-service
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABIITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - microservices-network
  book-service:
    image: pabloaugustocm/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - api-gateway
      - book-db
      - rabbit-mq
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin
      SPRING.FLYWAY.SCHEMAS: book-service
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABIITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - microservices-network
  zipkin:
    image: openzipkin/zipkin:2.24.1
    restart: always
    ports:
      - "9411:9411"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    depends_on:
      - rabbit-mq
    networks:
      - microservices-network
  rabbit-mq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
