server:
  port: 8002

resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      find-book:
        max-attempts: 2
        wait-duration: 1s
        enable-exponential-backoff: true
        # Tempo de espera esponencial em fibonacci

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${JDBC_URL}
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    url: ${DB_URL}
    schemas: ${SCHEMA}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: book-service/v3/api-docs