spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
greeting-service:
  greeting: "Hello"
  default_value: "Mundo"


server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'