name: Integração ao Github

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Logando Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
         java-version: '17'
         
      - name: Build Eureka Server
        working-directory: ./naming-server/
        run: mvn spring-boot:build-image -DskipTests
       
      - name: Build Api Gateway
        working-directory: ./api-gateway/
        run: mvn spring-boot:build-image -DskipTests 
      
      - name: Build Cambio Service
        working-directory: ./cambio-service/
        run: mvn clean package -DskipTests
        
      - name: Build Book Service
        working-directory: ./book-service/
        run: mvn clean package -DskipTests  
        
      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build  
