name: Criação de PR

on:
  push:
    branches:
      - teste	  
jobs:	  
 build:
  runs-on: ubuntu-latest
  steps:
  
  - name: Checkout
    uses: actions/checkout@v3
  
  - name: Cria PR
    uses: peter-evans/create-pull-request@v3
    with:
      base: main
      branch: teste
      token : ${{secrets.GITHUB_TOKEN}}
